theme: jekyll-theme-midnight
title: Welcome to my homepage!
description: Hey there, my name is Celina. If you want to see what I created so far please feel free to check out my site and try my games.

# About me
I'm a 20 years old gamedesign/programming student who enjoys to play and create different games. My complete life resolve around games, from playing to creating and sometimes writing.
I hope that people enjoy my work and that I can work with a great team to entertain more hardcore gamer and occasion gamer with my projects.
Currently I'm studying 3D-Game Design at the GPB College in Berlin, Germany. My specialization lies in gamedesign and programming, where I enjoy really to create new stories and technics.
